version: "3"
services:
    web:
        image: nginx:1.21.6
        container_name: hp_nginx
        restart: always
        links:
            - site
        volumes:
            - ./server.conf:/etc/nginx/conf.d/default.conf
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./data/logs:/logs
            - ..:/heisse-preise
        networks:
            - hp_network
    site:
        build:
            dockerfile: Dockerfile.site
            context: .
        container_name: hp_site
        restart: always
#        links:
#            - elasticsearch
        environment:            
            - HP_ADMIN_TOKEN=${HP_ADMIN_TOKEN}
        volumes:
            - ..:/heisse-preise
            - ./data/:/heisse-preise/data
        networks:
            - hp_network
#    elasticsearch:
#        image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
#        container_name: hp_elasticsearch
#        restart: always
#        environment:
#            - discovery.type=single-node
#        ports:
#            - 9200:9200
#            - 9300:9300
#        networks:
#            - hp_network

networks:
    hp_network:
        driver: bridge
