name: Pages Update

on:
  schedule:
    - cron: "0 8 * * *"
  push:
  workflow_dispatch:

jobs:
  run-script:
    name: Execute pages.sh
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script
      run: |
        git config --global user.email "badlogicgames@gmail.com"
        git config --global user.name "badlogic"
        ./pages.sh https://github.com/badlogic/badlogic.github.io